-- Supabase SQL Editor-এ একবার চালান
create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  father text,
  mother text,
  spouse text,
  dob text,
  village text,
  age integer,
  death_reason text,
  date text,
  death_date text,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Public app-এর জন্য profile read/search
create policy "Public can read profiles"
on public.profiles for select
to anon, authenticated
using (true);

-- Admin-only insert/update/delete করার জন্য পরে Supabase Auth + admin role policy ব্যবহার করুন.
-- এই starter-এ admin.html সরাসরি public insert করার আগে অবশ্যই Auth/RLS policy শক্ত করুন.

-- Profile Photo Storage
insert into storage.buckets (id, name, public)
values ('profile-photos', 'profile-photos', true)
on conflict (id) do update set public = true;

-- NOTE: এই public policies starter/demo ব্যবহারের জন্য।
-- Production-এ Admin Auth চালু করার পর এগুলো admin-only policy দিয়ে বদলান.
create policy "Public can view profile photos"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'profile-photos');

create policy "Public can upload profile photos"
on storage.objects for insert
to anon, authenticated
with check (bucket_id = 'profile-photos');


-- Authenticated Admin CRUD starter policies.
-- For production, restrict these policies further using a dedicated admin role/profile table.
create policy "Authenticated users can insert profiles"
on public.profiles for insert to authenticated
with check (true);

create policy "Authenticated users can update profiles"
on public.profiles for update to authenticated
using (true) with check (true);

create policy "Authenticated users can delete profiles"
on public.profiles for delete to authenticated
using (true);
